name: "Update Homebrew Tap Formula contents"

on:
  schedule:
    - cron: "0 * * * *" # daily
  workflow_dispatch:
    inputs:
      target:
        description: "The target repository to update"
        required: false

permissions:
  contents: write

env:
  VERSION: "0.0.7"

jobs:
  update-readme:
    name: "Update Homebrew Formula details"
    runs-on: ubuntu-24.04
    steps:

      - name: "Checkout repository"
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install application to render the template
        uses: supplypike/setup-bin@v4
        with:
          uri: "https://github.com/patrickdappollonio/homebrew-tap/releases/download/v${{ env.VERSION }}/homebrew-tap_linux_x86_64.tar.gz"
          name: "homebrew-tap"
          version: "${{ env.VERSION }}"

      - name: Configure timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "America/New_York"

      - name: Run application to generate Formulas
        run: |
          rm -rf Formula/*.rb README.md
          homebrew-tap --readme-template readme.md.gotmpl --target "${{ github.event.inputs.target }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update repository with refreshed details
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/ README.md || echo "No changes to add"
          git commit -m "[ci skip] Update Homebrew Tap formulas" || echo "No changes to commit"
          git push || echo "No changes to push"
